language: none

resources:
  - name: azure_cli_configuration
    type: cliConfig
    integration: Azure (Chatbot Experiments)

  - name: github_chatbot_170_infrastructure
    type: gitRepo
    integration: github
    pointer:
      sourceName: RichardSlater/chatbot-170-infrastructure
      branch: master

  - name: amido-chatbots-notify
    type: notification
    integration: amido-chatbots
    versionTemplate:
      recipients:
        - "#chatbots"

jobs:
  - name: infrastructure-provisioning
    type: runCLI
    steps:
      - IN: github_chatbot_170_infrastructure
      - IN: azure_cli_configuration
      - TASK:
        - script: >
            export
            ARM_SUBSCRIPTION_ID=$AZURE_CLI_CONFIGURATION_SUBSCRIPTIONID
            ARM_CLIENT_ID=$AZURE_CLI_CONFIGURATION_USERNAME
            ARM_CLIENT_SECRET=$AZURE_CLI_CONFIGURATION_PASSWORD
            ARM_TENANT_ID=$AZURE_CLI_CONFIGURATION_TENANTID
        - script: |
            cd $GITHUB_CHATBOT_170_INFRASTRUCTURE_STATE
            terraform apply
    on_success:
      - script: echo "SUCCESS"
    on_failure:
      - script: echo "FAILURE"
