resources:
  - name: azCliConfig
    type: cliConfig
    integration: Azure (Chatbot Experiments)

  - name: githubChatBot170Infra
    type: gitRepo
    integration: github
    pointer:
      sourcename: RichardSlater/chatbot-170-infrastructure
      branch: master

jobs:
  - name: infrastructure-provisioning
    type: runSh
    steps:
      - IN: githubChatBot170Infra
      - IN: azCliConfig
      - TASK:
        - script: >
            export ARM_SUBSCRIPTION_ID=$AZCLICONFIG_INTEGRATION_SUBSCRIPTIONID ARM_CLIENT_ID=$AZCLICONFIG_INTEGRATION_USERNAME ARM_CLIENT_SECRET=$AZCLICONFIG_INTEGRATION_PASSWORD ARM_TENANT_ID=$AZCLICONFIG_INTEGRATION_TENANTID

        # Execute Terraform script
        - script: |
            terraform apply --auto-approve
