language: none

resources:
  - name: azure_cli_configuration
    type: cliConfig
    integration: Azure (Chatbot Experiments)

  - name: github_chatbot_170_infrastructure
    type: gitRepo
    integration: github
    pointer:
      sourceName: RichardSlater/chatbot-170-infrastructure
      branch: master

  - name: amido-chatbots-notify
    type: notification
    integration: amido-chatbots
    versionTemplate:
      recipients:
        - "#chatbots"

jobs:
  - name: provisioning-infrastructure
    type: runSh
    steps:
      - IN: github_chatbot_170_infrastructure
      - IN: azure_cli_configuration
      - TASK:
        - script: |
            export TF_VERSION=0.11.4
            export TF_FILE=terraform_"$TF_VERSION"_linux_amd64.zip
            mkdir -p /tmp/terraform
            wget -nv https://releases.hashicorp.com/terraform/$TF_VERSION/$TF_FILE
            unzip -o $TF_FILE -d /tmp/terraform
            sudo chmod +x /tmp/terraform/terraform
            mv /tmp/terraform/terraform /usr/bin/terraform
            terraform --version
        - script: >
            export
            ARM_SUBSCRIPTION_ID="$(az account show --query "{id:id}" --output tsv)"
            ARM_CLIENT_ID=$AZURE_CLI_CONFIGURATION_INTEGRATION_APPID
            ARM_CLIENT_SECRET=$AZURE_CLI_CONFIGURATION_INTEGRATION_PASSWORD
            ARM_TENANT_ID=$AZURE_CLI_CONFIGURATION_INTEGRATION_TENANT
        - script: |
            cd $GITHUB_CHATBOT_170_INFRASTRUCTURE_STATE
            terraform --version
            terraform init
            terraform get
            terraform apply --auto-approve
    on_success:
      - script: echo "SUCCESS"
    on_failure:
      - script: echo "FAILURE"
