#!/bin/bash

export ARM_SUBSCRIPTION_ID="$(az account show --query "{id:id}" --output tsv)"
export ARM_CLIENT_ID=$AZURE_CLI_CONFIGURATION_INTEGRATION_APPID
export ARM_CLIENT_SECRET=$AZURE_CLI_CONFIGURATION_INTEGRATION_PASSWORD
export ARM_TENANT_ID=$AZURE_CLI_CONFIGURATION_INTEGRATION_TENANT
