export
ARM_SUBSCRIPTION_ID="$(az account show --query "{id:id}" --output tsv)"
ARM_CLIENT_ID=$AZURE_CLI_CONFIGURATION_INTEGRATION_APPID
ARM_CLIENT_SECRET=$AZURE_CLI_CONFIGURATION_INTEGRATION_PASSWORD
ARM_TENANT_ID=$AZURE_CLI_CONFIGURATION_INTEGRATION_TENANT
